name: Notify Upcoming Webinars

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  call-vercel-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel Endpoint
        run: |
          curl -i --fail --show-error \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            'https://coach-dashboard-alpha.vercel.app/api/cron/notify-upcoming-webinars'
